# Generated by Django 5.2.11 on 2026-02-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="cod", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="pincode",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="street",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
