# Generated by Django 5.2.11 on 2026-02-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_order_city_order_payment_method_order_pincode_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_index",
                    models.IntegerField(help_text="Sequence 0-5", unique=True),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("image", models.ImageField(upload_to="banners/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "banners",
                "ordering": ["slot_index"],
            },
        ),
    ]
