# Generated by Django 5.2.11 on 2026-02-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(default="General", max_length=100),
        ),
    ]
