# Generated by Django 5.2.11 on 2026-03-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
